// enum DepartmentEnum {
//     VEGETABLES
//     SWEETS
//     FISHES
//     FRUITS
//     DRINKS
//     BAKERY
//     # Přidejte další oddělení podle potřeby
//   }

//   enum VegetableCategoryEnum {
//     ROOT_VEGETABLES
//     LEAFY_VEGETABLES
//     FRUIT_VEGETABLES
//     ALLIUMS
//     TUBER_VEGETABLES
//     # Přidejte další kategorie zeleniny podle potřeby
//   }

//   enum SweetCategoryEnum {
//     CHOCOLATE
//     CANDY
//     SWEET_BAKERY
//     SALT_BAKERY
//     # Přidejte další kategorie sladkostí podle potřeby
//   }

//   enum FruitCategoryEnum {
//     TROPICAL_FRUIT
//     HOME_FRUIT
//     # Přidejte další kategorie ovoce podle potřeby
//   }

//   enum DrinkCategoryEnum {
//     NONALCOHOL
//     ALCOHOL
//     # Přidejte další kategorie nápojů podle potřeby
//   }

//   enum BakeryCategoryEnum {
//     SWEET_BAKERY
//     SALT_BAKERY
//     # Přidejte další kategorie pekárny podle potřeby
//   }
